include:
  - https://gitlab.ddgcorp.ru/devops/ci/raw/master/build_docker.yml
  - https://gitlab.ddgcorp.ru/devops/ci/raw/master/deploy_compose.yml

stages:
  - build
  - deploy:stage0

build:docker:
  when: manual
  allow_failure: false
  tags:
    - teorema
  stage: build
  extends: .build_docker
  before_script:
    - wget --header 'private-token: ${CI_JOB_TOKEN}' -qO 123.zip "https://gitlab.ddgcorp.ru/manzoni/ocular_front_mobile/-/jobs/artifacts/master/download?job=build" 
      && ls -l && cat 123.zip
    - mv ./artifacts/dist/teorema-mobile ./src/ocular_front_mobile
    - sh -c "
      cd src
      && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddgcorp.ru/manzoni/ocular_front.git
      && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddgcorp.ru/manzoni/ocular_pi.git
      && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddgcorp.ru/manzoni/ocular_qadrator.git
      && git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddgcorp.ru/manzoni/teorema.git
      && git clone https://github.com/PimenovAlexander/qhttpserver.git
      && git clone --branch 'release/4.1' --depth '1' https://github.com/FFmpeg/FFmpeg.git
      "
deploy:stage0:
  stage: deploy:stage0
  extends: .deploy_compose
  tags:
    - ocular