version: '3.4'

services:
  ocular:
    image: docker.ddgcorp.ru/manzoni/ocular_container:latest
    build: .
    restart: always
    tty: true
    ports:
      - 80:80
      - 1935:1935
      - 5005:5005
      - 5006:5006
      - 8080:8080
      - 8088:8088
      - 8188:8188
    networks:
      nw:
        ipv4_address: 10.10.110.10
    volumes:
      - pg:/var/lib/postgresql/9.5/main
      - pi:/home/_processInstances
      - va:/home/_VideoArchive

networks:
  nw:
    ipam:
      config:
        - subnet: 10.10.110.0/28

volumes:
  pg:
  pi:
  va:
