#!/bin/bash
service cron start
service postgresql start
cat /var/lib/postgresql/9.5/main/.MARK &>2 /dev/null || docker_firstrun

#cd /var/www/teorema
#source /var/www/teorema/env/bin/activate
#python3 manage.py makemigrations cameras orgs other users --noinput
#python3 manage.py migrate --noinput
#deactivate

supervisord
