#!/bin/bash

# make django forgot about some app-specific old migrations (before 15.4.19)
su - postgres -c "psql -c \"delete from django_migrations where app in ('orgs', 'users', 'cameras', 'admin', 'authtoken');\""

# make django think all old migrations (before 15.4.19) are applied
python3 manage.py migrate --fake --noinput orgs 0001_initial
python3 manage.py migrate --fake --noinput users 0001_initial
python3 manage.py migrate --fake --noinput admin 0001_initial
python3 manage.py migrate --fake --noinput admin 0002_logentry_remove_auto_add
python3 manage.py migrate --fake --noinput authtoken 0001_initial
python3 manage.py migrate --fake --noinput authtoken 0002_auto_20160226_1747
python3 manage.py migrate --fake --noinput cameras 0001_initial
python3 manage.py migrate --fake --noinput cameras 0002_auto_20190415_0248

# apply new migrations (after 15.4.19) if exists
python3 manage.py migrate --noinput 

